"""Bursa meşhur yemekleri — SEO içerik sayfaları."""
from __future__ import annotations

FAMOUS_FOODS = (
    {
        "slug": "bursa-iskender",
        "key": "iskender",
        "title": "İskender",
        "emoji": "🥙",
        "img": "/static/food/ne-yenir-iskender.jpg",
        "history": (
            "İskender kebap, 19. yüzyılda Bursa’da İskender Efendi tarafından geliştirilen "
            "pide üstü döner, tereyağı ve yoğurtla servis edilen klasik Bursa yemeğidir."
        ),
        "where": "Osmangazi / Heykel ve Tarihi Çarşı civarı en bilinen adreslerdir.",
        "price_level": "₺₺₺",
        "est_tl": 450,
        "subcategory": "iskender",
        "tags": ["iskender", "kebap"],
        "seo_title": "Bursa İskender Nerede Yenir? | BursaApp",
        "seo_desc": "Bursa İskender’in tarihçesi, fiyat seviyesi ve en iyi mekanlar — BursaApp.",
    },
    {
        "slug": "bursa-inegol-kofte",
        "key": "inegol-kofte",
        "title": "İnegöl Köfte",
        "emoji": "🥩",
        "img": "/static/food/ne-yenir-inegol-kofte.jpg",
        "history": "İnegöl köftesi, 19. yüzyılda Balkan göçmenleriyle İnegöl’e yerleşen et kültürünün ürünüdür.",
        "where": "İnegöl merkez ve Bursa genelinde köfteciler.",
        "price_level": "₺₺",
        "est_tl": 280,
        "subcategory": "inegol-kofte",
        "tags": ["kofte", "inegol"],
        "seo_title": "İnegöl Köfte Nerede Yenir? | BursaApp",
        "seo_desc": "İnegöl köfte tarihçesi ve Bursa’daki en iyi adresler.",
    },
    {
        "slug": "bursa-kemalpasa",
        "key": "kemalpasa",
        "title": "Kemalpaşa Tatlısı",
        "emoji": "🍮",
        "img": "/static/food/ne-yenir-kemalpasa.jpg",
        "history": "Mustafakemalpaşa’ya özgü peynirli, şerbetli tatlı; Bursa’nın imza tatlılarından.",
        "where": "Mustafakemalpaşa ve Bursa pastaneleri.",
        "price_level": "₺",
        "est_tl": 120,
        "subcategory": "tatli",
        "tags": ["kemalpasa", "tatli"],
        "seo_title": "Kemalpaşa Tatlısı | BursaApp",
        "seo_desc": "Kemalpaşa tatlısı nedir, nerede yenir?",
    },
    {
        "slug": "bursa-pideli-kofte",
        "key": "pideli-kofte",
        "title": "Pideli Köfte",
        "emoji": "🥘",
        "img": "/static/food/ne-yenir-pideli-kofte.jpg",
        "history": "Pide üzerinde köfte, yoğurt ve tereyağı — Bursa’nın ev usulü klasiklerinden.",
        "where": "Osmangazi ve Nilüfer’deki geleneksel lokantalar.",
        "price_level": "₺₺",
        "est_tl": 320,
        "subcategory": "pide",
        "tags": ["pideli-kofte", "kofte"],
        "seo_title": "Pideli Köfte Bursa | BursaApp",
        "seo_desc": "Bursa pideli köfte mekanları ve fiyat seviyesi.",
    },
    {
        "slug": "bursa-kestane-sekeri",
        "key": "kestane-sekeri",
        "title": "Kestane Şekeri",
        "emoji": "🌰",
        "img": "/static/food/ne-yenir-kestane.jpg",
        "history": "Bursa’nın hediyelik simgesi; şekerlenmiş kestane geleneksel üretimle bilinir.",
        "where": "Çarşı, hanlar ve hediyelik dükkânları.",
        "price_level": "₺₺",
        "est_tl": 200,
        "subcategory": "tatli",
        "tags": ["kestane", "hediye"],
        "seo_title": "Bursa Kestane Şekeri | BursaApp",
        "seo_desc": "Bursa kestane şekeri nereden alınır?",
    },
    {
        "slug": "bursa-sut-helvasi",
        "key": "sut-helvasi",
        "title": "Süt Helvası",
        "emoji": "🍰",
        "img": "/static/food/ne-yenir-sut-helvasi.jpg",
        "history": "Süt, un ve şekerle yapılan yumuşak helva; Bursa’da pastane klasikleri arasındadır.",
        "where": "Tarihi pastaneler ve tatlıcılar.",
        "price_level": "₺",
        "est_tl": 100,
        "subcategory": "tatli",
        "tags": ["helva", "tatli"],
        "seo_title": "Bursa Süt Helvası | BursaApp",
        "seo_desc": "Bursa süt helvası nerede yenir?",
    },
)

FOOD_BY_SLUG = {f["slug"]: f for f in FAMOUS_FOODS}
